package Gui;
import static Gui.AdminList.fm;
import finalproject.FundraiserManager;
public class AdminViewDonor extends javax.swing.JFrame {
    static FundraiserManager fm=new FundraiserManager();
    public AdminViewDonor(FundraiserManager fm) {
        initComponents();
        this.fm=fm;
        String print=fm.displayDonorsforAdmins();
        txtDisplayDonor.setText(print);
        setExtendedState(this.MAXIMIZED_BOTH);
        txtDisplayDonor.setEditable(false);
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        txtDisplayDonor = new javax.swing.JTextArea();
        btnViewF2 = new javax.swing.JButton();
        btnAddFR1 = new javax.swing.JButton();
        btnDelete = new javax.swing.JButton();
        btnExpired1 = new javax.swing.JButton();
        btnCompleted1 = new javax.swing.JButton();
        btnAddDonor1 = new javax.swing.JButton();
        btnViewD1 = new javax.swing.JButton();
        btnHome1 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Georgia", 0, 36)); // NOI18N
        jLabel1.setText("VIEW DONORS OF OUR ORGANIZATION");

        txtDisplayDonor.setColumns(20);
        txtDisplayDonor.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        txtDisplayDonor.setRows(5);
        jScrollPane1.setViewportView(txtDisplayDonor);

        btnViewF2.setFont(new java.awt.Font("Constantia", 1, 14)); // NOI18N
        btnViewF2.setText("VIEW FUNDRAISER");
        btnViewF2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnViewF2ActionPerformed(evt);
            }
        });

        btnAddFR1.setFont(new java.awt.Font("Constantia", 1, 14)); // NOI18N
        btnAddFR1.setText("ADD FUNDRAISER");
        btnAddFR1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAddFR1ActionPerformed(evt);
            }
        });

        btnDelete.setFont(new java.awt.Font("Constantia", 1, 14)); // NOI18N
        btnDelete.setText("DELETE  FUNDRAISER");
        btnDelete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDeleteActionPerformed(evt);
            }
        });

        btnExpired1.setFont(new java.awt.Font("Constantia", 1, 14)); // NOI18N
        btnExpired1.setText("VIEW EXPIRED FUNDRAISER");
        btnExpired1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnExpired1ActionPerformed(evt);
            }
        });

        btnCompleted1.setFont(new java.awt.Font("Constantia", 1, 14)); // NOI18N
        btnCompleted1.setText("VIEW COMPLETED FUNDRAISER");
        btnCompleted1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCompleted1ActionPerformed(evt);
            }
        });

        btnAddDonor1.setFont(new java.awt.Font("Constantia", 1, 14)); // NOI18N
        btnAddDonor1.setText("ADD A DONOR");
        btnAddDonor1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAddDonor1ActionPerformed(evt);
            }
        });

        btnViewD1.setFont(new java.awt.Font("Constantia", 1, 14)); // NOI18N
        btnViewD1.setText("VIEW ALL DONORS");
        btnViewD1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnViewD1ActionPerformed(evt);
            }
        });

        btnHome1.setFont(new java.awt.Font("Constantia", 1, 24)); // NOI18N
        btnHome1.setText("HOME");
        btnHome1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnHome1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnHome1, javax.swing.GroupLayout.PREFERRED_SIZE, 257, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnExpired1, javax.swing.GroupLayout.PREFERRED_SIZE, 257, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnCompleted1)
                    .addComponent(btnAddDonor1, javax.swing.GroupLayout.PREFERRED_SIZE, 257, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnViewD1, javax.swing.GroupLayout.PREFERRED_SIZE, 257, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnDelete, javax.swing.GroupLayout.PREFERRED_SIZE, 257, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnViewF2, javax.swing.GroupLayout.PREFERRED_SIZE, 257, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnAddFR1, javax.swing.GroupLayout.PREFERRED_SIZE, 257, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 295, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 695, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 756, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(579, 579, 579))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(70, 70, 70)
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(88, 88, 88)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 535, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(90, 90, 90)
                        .addComponent(btnHome1, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(71, 71, 71)
                        .addComponent(btnViewF2, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(19, 19, 19)
                        .addComponent(btnAddFR1, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(19, 19, 19)
                        .addComponent(btnDelete, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(btnExpired1, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(26, 26, 26)
                        .addComponent(btnCompleted1, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(28, 28, 28)
                        .addComponent(btnAddDonor1, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(26, 26, 26)
                        .addComponent(btnViewD1, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(346, Short.MAX_VALUE))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btnViewF2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnViewF2ActionPerformed
        // TODO add your handling code here:
        AdminList aList=new AdminList(fm);
        aList.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btnViewF2ActionPerformed

    private void btnAddFR1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAddFR1ActionPerformed
        // TODO add your handling code here:
        AdminAddFr addFr=new AdminAddFr(fm);
        addFr.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btnAddFR1ActionPerformed

    private void btnDeleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDeleteActionPerformed
        // TODO add your handling code here:
        AdminDelete del=new AdminDelete(fm);
        del.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btnDeleteActionPerformed

    private void btnExpired1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnExpired1ActionPerformed
        // TODO add your handling code here:
        AdminExpired adminExp=new AdminExpired(fm);
        adminExp.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btnExpired1ActionPerformed

    private void btnCompleted1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCompleted1ActionPerformed
        // TODO add your handling code here:
        AdminComplete complete=new AdminComplete(fm);
        complete.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btnCompleted1ActionPerformed

    private void btnAddDonor1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAddDonor1ActionPerformed
        // TODO add your handling code here:
        AdminAddDonor addDonor=new AdminAddDonor(fm);
        addDonor.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btnAddDonor1ActionPerformed

    private void btnViewD1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnViewD1ActionPerformed
        // TODO add your handling code here:
        AdminViewDonor viewDonor=new AdminViewDonor(fm);
        viewDonor.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btnViewD1ActionPerformed

    private void btnHome1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnHome1ActionPerformed
        // TODO add your handling code here:
        Home h=new Home(fm);
        h.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btnHome1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(AdminViewDonor.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(AdminViewDonor.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(AdminViewDonor.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(AdminViewDonor.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new AdminViewDonor(fm).setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAddDonor1;
    private javax.swing.JButton btnAddFR1;
    private javax.swing.JButton btnCompleted1;
    private javax.swing.JButton btnDelete;
    private javax.swing.JButton btnExpired1;
    private javax.swing.JButton btnHome1;
    private javax.swing.JButton btnViewD1;
    private javax.swing.JButton btnViewF2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextArea txtDisplayDonor;
    // End of variables declaration//GEN-END:variables
}
