 package Gui;

import com.toedter.calendar.JDateChooser;
import com.toedter.calendar.JTextFieldDateEditor;
import java.text.SimpleDateFormat;
import finalproject.Fundraiser;
import finalproject.FundraiserManager;
import finalproject.DataBase;

import java.util.Calendar;
import java.util.Date;
import javax.swing.JOptionPane;
public class AdminAddFr extends javax.swing.JFrame {
    
    static FundraiserManager fm=new FundraiserManager();
    JTextFieldDateEditor dtEditStart;
    JTextFieldDateEditor dtEditEnd;
    
    public AdminAddFr(FundraiserManager fm) {
        initComponents();
        uneditDate();
        setExtendedState(this.MAXIMIZED_BOTH);
        this.fm=fm;
    }
    private void uneditDate(){
        dtEditStart=(JTextFieldDateEditor) dateS.getDateEditor();
        dtEditStart.setEditable(false);
        dtEditEnd=(JTextFieldDateEditor) dateE.getDateEditor();
        dtEditEnd.setEditable(false);
    }
    private String dateFormat(Date date){
        try {
            SimpleDateFormat dtFormat=new SimpleDateFormat("dd/MM/yyyy");
            return dtFormat.format(date);
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, "Error: "+e);
            return "";
        }
    }
    private boolean checkFields(){
        if (txtAmount.getText().isEmpty() || txtName.getText().isEmpty()|| txtDescription.getText().isEmpty() || dateS.getDate().equals(null) || dateE.getDate().equals(null)) {
            return false;
        }
        else
            return true;
    }
    private void setFieldsEmpty(){
        txtName.setText("");
        txtAmount.setText(null);
        txtDescription.setText(null);
        dateS.setCalendar(null);
        dateE.setCalendar(null);
    }
    public boolean validateEndDate(JDateChooser dateChooser) {
        Date selectedDate = dateChooser.getDate();

        Date currentDate = new Date();
        Calendar calendar = Calendar.getInstance();
        calendar.setTime(currentDate);
        calendar.set(Calendar.HOUR_OF_DAY, 0);
        calendar.set(Calendar.MINUTE, 0);
        calendar.set(Calendar.SECOND, 0);
        calendar.set(Calendar.MILLISECOND, 0);
        currentDate = calendar.getTime();

        // Compare the selected date with the current date
        if (selectedDate.before(currentDate)) {
            JOptionPane.showMessageDialog(this, "END DATE CANNOT BE BEFORE CURRENT DATE", "Invalid Date", JOptionPane.ERROR_MESSAGE);
            return false;
        }

        return true;
    
    }
    
     public boolean validateStartDate(JDateChooser dateChooser) {
        Date selectedDate = dateChooser.getDate();

        Date currentDate = new Date();
        Calendar calendar = Calendar.getInstance();
        calendar.setTime(currentDate);
        calendar.set(Calendar.HOUR_OF_DAY, 0);
        calendar.set(Calendar.MINUTE, 0);
        calendar.set(Calendar.SECOND, 0);
        calendar.set(Calendar.MILLISECOND, 0);
        currentDate = calendar.getTime();

        // Compare the selected date with the current date
        if (selectedDate.before(currentDate) || selectedDate.after(currentDate)) {
            JOptionPane.showMessageDialog(this, "SELECT START DATE AS THE CURRENT DATE", "Invalid Date", JOptionPane.ERROR_MESSAGE);
            return false;
        }

        return true;
    
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        txtName = new javax.swing.JTextField();
        txtDescription = new javax.swing.JTextField();
        dateS = new com.toedter.calendar.JDateChooser();
        dateE = new com.toedter.calendar.JDateChooser();
        txtAmount = new javax.swing.JTextField();
        btnUpdate = new javax.swing.JButton();
        btnViewF = new javax.swing.JButton();
        btnAddFR = new javax.swing.JButton();
        btnDelete = new javax.swing.JButton();
        btnExpired = new javax.swing.JButton();
        btnCompleted = new javax.swing.JButton();
        btnAddDonor = new javax.swing.JButton();
        btnViewD = new javax.swing.JButton();
        btnHome2 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Trebuchet MS", 0, 36)); // NOI18N
        jLabel1.setText("ADD A FUNDRAISER");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(842, 78, 327, 55));

        jLabel2.setFont(new java.awt.Font("Yu Gothic UI Semibold", 1, 18)); // NOI18N
        jLabel2.setText("CAMPAIGN NAME:");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(779, 217, 176, 36));

        jLabel3.setFont(new java.awt.Font("Yu Gothic UI Semibold", 1, 18)); // NOI18N
        jLabel3.setText("DESCRIPTION:");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(779, 271, 176, 36));

        jLabel4.setFont(new java.awt.Font("Yu Gothic UI Semibold", 1, 18)); // NOI18N
        jLabel4.setText("START DATE:");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(779, 341, 176, 36));

        jLabel5.setFont(new java.awt.Font("Yu Gothic UI Semibold", 1, 18)); // NOI18N
        jLabel5.setText("TARGET AMOUNT:");
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(779, 458, 176, 36));

        jLabel6.setFont(new java.awt.Font("Yu Gothic UI Semibold", 1, 18)); // NOI18N
        jLabel6.setText("END DATE");
        getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(779, 395, 176, 36));

        txtName.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        getContentPane().add(txtName, new org.netbeans.lib.awtextra.AbsoluteConstraints(987, 217, 253, 36));

        txtDescription.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        getContentPane().add(txtDescription, new org.netbeans.lib.awtextra.AbsoluteConstraints(987, 271, 253, 36));

        dateS.setDateFormatString("dd/MM/yyyy");
        getContentPane().add(dateS, new org.netbeans.lib.awtextra.AbsoluteConstraints(987, 341, 253, 36));

        dateE.setDateFormatString("dd/MM/yyyy");
        getContentPane().add(dateE, new org.netbeans.lib.awtextra.AbsoluteConstraints(987, 395, 253, 36));

        txtAmount.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        getContentPane().add(txtAmount, new org.netbeans.lib.awtextra.AbsoluteConstraints(987, 458, 253, 36));

        btnUpdate.setFont(new java.awt.Font("Tahoma", 0, 36)); // NOI18N
        btnUpdate.setText("ADD FUNDRAISER");
        btnUpdate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnUpdateActionPerformed(evt);
            }
        });
        getContentPane().add(btnUpdate, new org.netbeans.lib.awtextra.AbsoluteConstraints(810, 580, 390, -1));

        btnViewF.setFont(new java.awt.Font("Constantia", 1, 14)); // NOI18N
        btnViewF.setText("VIEW FUNDRAISER");
        btnViewF.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnViewFActionPerformed(evt);
            }
        });
        getContentPane().add(btnViewF, new org.netbeans.lib.awtextra.AbsoluteConstraints(12, 185, 257, 51));

        btnAddFR.setFont(new java.awt.Font("Constantia", 1, 14)); // NOI18N
        btnAddFR.setText("ADD FUNDRAISER");
        btnAddFR.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAddFRActionPerformed(evt);
            }
        });
        getContentPane().add(btnAddFR, new org.netbeans.lib.awtextra.AbsoluteConstraints(12, 255, 257, 51));

        btnDelete.setFont(new java.awt.Font("Constantia", 1, 14)); // NOI18N
        btnDelete.setText("DELETE  FUNDRAISER");
        btnDelete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDeleteActionPerformed(evt);
            }
        });
        getContentPane().add(btnDelete, new org.netbeans.lib.awtextra.AbsoluteConstraints(12, 325, 257, 51));

        btnExpired.setFont(new java.awt.Font("Constantia", 1, 14)); // NOI18N
        btnExpired.setText("VIEW EXPIRED FUNDRAISER");
        btnExpired.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnExpiredActionPerformed(evt);
            }
        });
        getContentPane().add(btnExpired, new org.netbeans.lib.awtextra.AbsoluteConstraints(12, 389, 257, 51));

        btnCompleted.setFont(new java.awt.Font("Constantia", 1, 14)); // NOI18N
        btnCompleted.setText("VIEW COMPLETED FUNDRAISER");
        btnCompleted.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCompletedActionPerformed(evt);
            }
        });
        getContentPane().add(btnCompleted, new org.netbeans.lib.awtextra.AbsoluteConstraints(12, 466, -1, 51));

        btnAddDonor.setFont(new java.awt.Font("Constantia", 1, 14)); // NOI18N
        btnAddDonor.setText("ADD A DONOR");
        btnAddDonor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAddDonorActionPerformed(evt);
            }
        });
        getContentPane().add(btnAddDonor, new org.netbeans.lib.awtextra.AbsoluteConstraints(12, 545, 257, 51));

        btnViewD.setFont(new java.awt.Font("Constantia", 1, 14)); // NOI18N
        btnViewD.setText("VIEW ALL DONORS");
        btnViewD.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnViewDActionPerformed(evt);
            }
        });
        getContentPane().add(btnViewD, new org.netbeans.lib.awtextra.AbsoluteConstraints(12, 622, 257, 51));

        btnHome2.setFont(new java.awt.Font("Constantia", 1, 24)); // NOI18N
        btnHome2.setText("HOME");
        btnHome2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnHome2ActionPerformed(evt);
            }
        });
        getContentPane().add(btnHome2, new org.netbeans.lib.awtextra.AbsoluteConstraints(12, 63, 257, 51));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btnUpdateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnUpdateActionPerformed
        // TODO add your handling code here:
        if (checkFields()) {
                String name=txtName.getText();
                String des=txtDescription.getText();
                String startDate=dateFormat(dateS.getDate());
                Boolean validationStartDate=validateStartDate(dateS);
                if (!validationStartDate) {
                   setFieldsEmpty();
                    return;
                }
                Boolean validationEndDate=validateEndDate(dateE);
                if (!validationEndDate) {
                    setFieldsEmpty();
                    return;
                }
                String endDate=dateFormat(dateE.getDate());
                double amount=Double.parseDouble(txtAmount.getText());
                Fundraiser fr=new Fundraiser(name, des, startDate,endDate, amount, 0.0);
                fm.addFundRaiser(fr);
                setFieldsEmpty();
                DataBase db=new DataBase();
                String result=db.addFRtoDB(name, startDate, endDate, des, amount);
                JOptionPane.showMessageDialog(this, result);
        }
        else{
            JOptionPane.showMessageDialog(this, "FIELDS EMPTY");
            return;
            }
      
        
    }//GEN-LAST:event_btnUpdateActionPerformed

    private void btnViewFActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnViewFActionPerformed
        // TODO add your handling code here:
        AdminList aList=new AdminList(fm);
        aList.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btnViewFActionPerformed

    private void btnAddFRActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAddFRActionPerformed
        // TODO add your handling code here:
        AdminAddFr addFr=new AdminAddFr(fm);
        addFr.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btnAddFRActionPerformed

    private void btnDeleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDeleteActionPerformed
        // TODO add your handling code here:
        AdminDelete del=new AdminDelete(fm);
        del.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btnDeleteActionPerformed

    private void btnExpiredActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnExpiredActionPerformed
        // TODO add your handling code here:
        AdminExpired adminExp=new AdminExpired(fm);
        adminExp.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btnExpiredActionPerformed

    private void btnCompletedActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCompletedActionPerformed
        // TODO add your handling code here:
        AdminComplete complete=new AdminComplete(fm);
        complete.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btnCompletedActionPerformed

    private void btnAddDonorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAddDonorActionPerformed
        // TODO add your handling code here:
        AdminAddDonor addDonor=new AdminAddDonor(fm);
        addDonor.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btnAddDonorActionPerformed

    private void btnViewDActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnViewDActionPerformed
        // TODO add your handling code here:
        AdminViewDonor viewDonor=new AdminViewDonor(fm);
        viewDonor.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btnViewDActionPerformed

    private void btnHome2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnHome2ActionPerformed
        // TODO add your handling code here:
        Home h=new Home(fm);
        h.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btnHome2ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(AdminAddFr.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(AdminAddFr.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(AdminAddFr.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(AdminAddFr.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new AdminAddFr(fm).setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAddDonor;
    private javax.swing.JButton btnAddFR;
    private javax.swing.JButton btnCompleted;
    private javax.swing.JButton btnDelete;
    private javax.swing.JButton btnExpired;
    private javax.swing.JButton btnHome2;
    private javax.swing.JButton btnUpdate;
    private javax.swing.JButton btnViewD;
    private javax.swing.JButton btnViewF;
    private com.toedter.calendar.JDateChooser dateE;
    private com.toedter.calendar.JDateChooser dateS;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JTextField txtAmount;
    private javax.swing.JTextField txtDescription;
    private javax.swing.JTextField txtName;
    // End of variables declaration//GEN-END:variables
}
