package Gui;
import finalproject.Donation;
import finalproject.Donor;
import finalproject.FundraiserManager;
import finalproject.DataBase;

import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import javax.swing.JOptionPane;

public class UserDonate extends javax.swing.JFrame {
    static FundraiserManager fm=new FundraiserManager();
    static Donor donor;
    static Donation donation;
    
    public UserDonate(FundraiserManager fm,Donor donor,Donation donation) {
        initComponents();
        txtList.setEditable(false);
        setExtendedState(this.MAXIMIZED_BOTH);
        this.fm=fm;
        this.donor=donor;
        this.donation=donation;
        display();
    }
    public void display(){
        String list=fm.viewFundRaisers();
        txtList.setText(list);
    }
    private boolean checkFields(){
        if (txtCompaign.getText().isEmpty() || txtDonation.getText().isEmpty()) {
            return false;
        }
        else
            return true;
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        txtList = new javax.swing.JTextArea();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        txtDonation = new javax.swing.JTextField();
        txtCompaign = new javax.swing.JTextField();
        btnDonate = new javax.swing.JButton();
        btnuserList = new javax.swing.JButton();
        btnuserDonate = new javax.swing.JButton();
        btnUserExpired = new javax.swing.JButton();
        btnUserCom = new javax.swing.JButton();
        btnViewDonors = new javax.swing.JButton();
        btnYourDon = new javax.swing.JButton();
        btnHome = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        txtList.setColumns(20);
        txtList.setFont(new java.awt.Font("Dubai Light", 1, 24)); // NOI18N
        txtList.setRows(5);
        jScrollPane1.setViewportView(txtList);

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel1.setText("ENTER THE AMOUNT YOU WANT TO DONATE: ");

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel2.setText("ENTER THE COMPAIGN NAME YOU WANT TO DONATE: ");

        txtDonation.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N

        txtCompaign.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        txtCompaign.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtCompaignActionPerformed(evt);
            }
        });

        btnDonate.setFont(new java.awt.Font("Serif", 0, 36)); // NOI18N
        btnDonate.setText("D O N A T E");
        btnDonate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDonateActionPerformed(evt);
            }
        });

        btnuserList.setFont(new java.awt.Font("Serif", 0, 14)); // NOI18N
        btnuserList.setText("V I E W  L I S T  O F  A L L  F U N D R A I S E R S");
        btnuserList.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnuserListActionPerformed(evt);
            }
        });

        btnuserDonate.setFont(new java.awt.Font("Serif", 0, 14)); // NOI18N
        btnuserDonate.setText("D O N A T E   T O  A V A I L A B L E  F U N D R A I S E R  ");
        btnuserDonate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnuserDonateActionPerformed(evt);
            }
        });

        btnUserExpired.setFont(new java.awt.Font("Serif", 0, 14)); // NOI18N
        btnUserExpired.setText("V I E W   E X P I R E D   C O M P A I G N S");
        btnUserExpired.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnUserExpiredActionPerformed(evt);
            }
        });

        btnUserCom.setFont(new java.awt.Font("Serif", 0, 14)); // NOI18N
        btnUserCom.setText("V I E W   C O M P L E T E D   C O M P A I G N S");
        btnUserCom.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnUserComActionPerformed(evt);
            }
        });

        btnViewDonors.setFont(new java.awt.Font("Serif", 0, 14)); // NOI18N
        btnViewDonors.setText("V I E W   O U R  D O N O R S");
        btnViewDonors.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnViewDonorsActionPerformed(evt);
            }
        });

        btnYourDon.setFont(new java.awt.Font("Serif", 0, 14)); // NOI18N
        btnYourDon.setText("V I E W  Y O U R  D O N A T I O N S");

        btnHome.setFont(new java.awt.Font("Serif", 1, 36)); // NOI18N
        btnHome.setText("H O M E");
        btnHome.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnHomeActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(btnViewDonors, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnUserCom, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnUserExpired, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnuserDonate, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                    .addComponent(btnuserList, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnYourDon, javax.swing.GroupLayout.DEFAULT_SIZE, 375, Short.MAX_VALUE)
                    .addComponent(btnHome, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(256, 256, 256)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(290, 290, 290)
                                .addComponent(btnDonate, javax.swing.GroupLayout.PREFERRED_SIZE, 300, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel2)
                                .addGap(6, 6, 6)
                                .addComponent(txtCompaign, javax.swing.GroupLayout.PREFERRED_SIZE, 310, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(70, 70, 70)
                                .addComponent(jLabel1)
                                .addGap(16, 16, 16)
                                .addComponent(txtDonation, javax.swing.GroupLayout.PREFERRED_SIZE, 310, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(361, 361, 361)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 624, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(129, 129, 129)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 513, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtCompaign, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtDonation, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(31, 31, 31)
                        .addComponent(btnDonate, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(btnHome)
                        .addGap(71, 71, 71)
                        .addComponent(btnuserList, javax.swing.GroupLayout.PREFERRED_SIZE, 66, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(36, 36, 36)
                        .addComponent(btnuserDonate, javax.swing.GroupLayout.PREFERRED_SIZE, 66, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(32, 32, 32)
                        .addComponent(btnUserExpired, javax.swing.GroupLayout.PREFERRED_SIZE, 66, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(33, 33, 33)
                        .addComponent(btnUserCom, javax.swing.GroupLayout.PREFERRED_SIZE, 66, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(33, 33, 33)
                        .addComponent(btnViewDonors, javax.swing.GroupLayout.PREFERRED_SIZE, 66, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(27, 27, 27)
                        .addComponent(btnYourDon, javax.swing.GroupLayout.PREFERRED_SIZE, 66, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(217, Short.MAX_VALUE))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void txtCompaignActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtCompaignActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtCompaignActionPerformed

    private void btnDonateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDonateActionPerformed
        // TODO add your handling code here:
        if (checkFields()) {
            DataBase db=new DataBase();
            String name=txtCompaign.getText();
            Double amount=Double.parseDouble(txtDonation.getText());
            Double check=fm.addDonationToFundRaiser(name,amount);
                        if (check!=0) {
                            Donation donation=new Donation(donor,amount,name);
                            fm.addDonor(donation);
                            fm.amountCompleted();
                            String result=db.addDonorToDB(donor.getName(), donor.getEmail(), donor.getPhoneNo(), donor.getDonationHistory(), donor.getAddress(), name, amount);
                            JOptionPane.showMessageDialog(this, result);
                            txtCompaign.setText("");
                            txtDonation.setText("");
                            result=db.updateFieldOfFundRaiser(name, check);
                            display();
                            
                        }
                        else{
                          JOptionPane.showMessageDialog(this, "ERROR IN DONATING");
                        }
        }
        else
            JOptionPane.showMessageDialog(this, "N O    F I E L D    S H O U L D    B E   L E F T   E M P T Y");
    }//GEN-LAST:event_btnDonateActionPerformed

    private void btnuserListActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnuserListActionPerformed
        // TODO add your handling code here:
        UserViewList list=new UserViewList(fm,donor,donation);
        list.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btnuserListActionPerformed

    private void btnuserDonateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnuserDonateActionPerformed
        // TODO add your handling code here:
        UserDonate donate=new UserDonate(fm, donor, donation);
        donate.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btnuserDonateActionPerformed

    private void btnUserExpiredActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnUserExpiredActionPerformed
        // TODO add your handling code here:
        UserViewExp exp=new UserViewExp(fm, donor, donation);
        exp.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btnUserExpiredActionPerformed

    private void btnUserComActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnUserComActionPerformed
        // TODO add your handling code here:
        UserViewComp com=new UserViewComp(fm, donor, donation);
        com.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btnUserComActionPerformed

    private void btnViewDonorsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnViewDonorsActionPerformed
        // TODO add your handling code here:
        UserViewDonor viewDonor=new UserViewDonor(fm, donor, donation);
        viewDonor.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btnViewDonorsActionPerformed

    private void btnHomeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnHomeActionPerformed
        // TODO add your handling code here:
        Home h=new Home(fm);
        h.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btnHomeActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(UserDonate.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(UserDonate.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(UserDonate.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(UserDonate.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new UserDonate(fm,donor,donation).setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnDonate;
    private javax.swing.JButton btnHome;
    private javax.swing.JButton btnUserCom;
    private javax.swing.JButton btnUserExpired;
    private javax.swing.JButton btnViewDonors;
    private javax.swing.JButton btnYourDon;
    private javax.swing.JButton btnuserDonate;
    private javax.swing.JButton btnuserList;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField txtCompaign;
    private javax.swing.JTextField txtDonation;
    private javax.swing.JTextArea txtList;
    // End of variables declaration//GEN-END:variables
}
